# For developer
name: Deploy for testint
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  publish_image:
    name: Publish Docker image
    uses: './.github/workflows/docker-publish.yml'
    secrets: inherit
    with:
      tags: zkmelabs/mechain:test


  deploy_with_k8s:
    name: Deploy with k8s
    uses: './.github/workflows/deploy-k8s.yml'
    needs: publish_image
    secrets: inherit
    with:
      namespace_k8s: mechain-test
      release_name: mechain-validator
      publish_tag: test
