# For developer
name: Deploy for devint
on:
  push:
    branches:
      - develop
      - feat/**
      - fea/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  publish_image:
    name: Publish Docker image
    uses: './.github/workflows/docker-publish.yml'
    secrets: inherit
    with:
      tags: zkmelabs/mechain:develop


  deploy_with_k8s:
    name: Deploy with k8s
    uses: './.github/workflows/deploy-k8s.yml'
    secrets: inherit
    with:
      namespace_k8s: mechain-dev
      release_name: mechain-validator
      publish_tag: develop
